/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opensource_androidffmpeg_utils_FFmpegTool */

#ifndef _Included_com_opensource_androidffmpeg_utils_FFmpegTool
#define _Included_com_opensource_androidffmpeg_utils_FFmpegTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    testLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_testLog
  (JNIEnv *, jclass);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_exit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    mergeVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_mergeVideo
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    cutVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_cutVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    addWaterMark
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_addWaterMark
  (JNIEnv *, jclass, jstring, jstring, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    removeAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_removeAudio
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    fetchAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_fetchAudio
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    addAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_addAudio
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_opensource_androidffmpeg_utils_FFmpegTool
 * Method:    ffmpeg
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_opensource_androidffmpeg_utils_FFmpegTool_ffmpeg
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif

/*****************************************************************************************************************/


/***************************************************************************************************/

///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    testLog
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_testLog
//  (JNIEnv *, jclass);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    exit
// * Signature: (I)V
// */
//JNIEXPORT void JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_exit
//  (JNIEnv *, jclass, jint);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    mergeVideo
// * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_mergeVideo
//  (JNIEnv *, jclass, jstring, jstring, jobjectArray);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    cutVideo
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_cutVideo
//  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    addWaterMark
// * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_addWaterMark
//  (JNIEnv *, jclass, jstring, jstring, jint, jstring, jstring, jstring, jstring);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    removeAudio
// * Signature: (Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_removeAudio
//  (JNIEnv *, jclass, jstring, jstring);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    fetchAudio
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_fetchAudio
//  (JNIEnv *, jclass, jstring, jstring, jstring);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    addAudio
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_addAudio
//  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);
//
///*
// * Class:     com_cn21_vgo_camcorder_utils_FFmpegTool
// * Method:    ffmpeg
// * Signature: ([Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_cn21_vgo_camcorder_utils_FFmpegTool_ffmpeg
//  (JNIEnv *, jclass, jobjectArray);
//
//#ifdef __cplusplus
//}
//#endif
//#endif

/******************************************************************************************************************/
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    testLog
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_testLog
//  (JNIEnv *, jclass);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    exit
// * Signature: (I)V
// */
//JNIEXPORT void JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_exit
//  (JNIEnv *, jclass, jint);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    mergeVideo
// * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_mergeVideo
//  (JNIEnv *, jclass, jstring, jstring, jobjectArray);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    cutVideo
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_cutVideo
//  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    addWaterMark
// * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_addWaterMark
//  (JNIEnv *, jclass, jstring, jstring, jint, jstring, jstring, jstring, jstring);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    removeAudio
// * Signature: (Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_removeAudio
//  (JNIEnv *, jclass, jstring, jstring);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    fetchAudio
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_fetchAudio
//  (JNIEnv *, jclass, jstring, jstring, jstring);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    addAudio
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_addAudio
//  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);
//
///*
// * Class:     com_opensource_camcorder_utils_FFmpegTool
// * Method:    ffmpeg
// * Signature: ([Ljava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_opensource_camcorder_utils_FFmpegTool_ffmpeg
//  (JNIEnv *, jclass, jobjectArray);
//
//#ifdef __cplusplus
//}
//#endif
//#endif

