/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opensource_ffmpeg_android_test_MainActivity */

#ifndef _Included_com_opensource_ffmpeg_android_test_MainActivity
#define _Included_com_opensource_ffmpeg_android_test_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opensource_ffmpeg_android_test_MainActivity
 * Method:    openFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_opensource_ffmpeg_android_test_MainActivity_openFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
